[package]
name = "sprowl"
version = "0.2.0"
authors = ["Cobrand <cobrandw@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
image = "^0.21"
gl = "^0.12"
cgmath = "^0.17"
rusttype = "^0.7"
fnv = "^1.0"
failure = "^0.1"

[dev-dependencies]
sdl2 = "^0.32"